runtime: nodejs22
env: standard

service: smarteco

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: 1.23

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
